{
 "title": "Ping, Pacotes e Latência",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(ping_rtt_worst_ms, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "IP's Monitorados",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ping_loss_percent{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "Porcentagem de perda de ping - PUBG",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", ip=\"150.109.27.214\"}",
     "legendFormat": "{{ip}}"
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", ip=\"201.159.159.129\"}",
     "legendFormat": "{{ip}}"
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", ip=\"169.57.199.205\"}",
     "legendFormat": "{{ip}}"
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", ip=\"49.51.42.110\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Tempo de Ida e Volta (RTT) - Serviços do Google",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"mail.google.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"mail.google.com\"})",
     "legendFormat": "{{Gmail}}"
    },
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"docs.google.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"docs.google.com\"})",
     "legendFormat": "{{Docs}}"
    },
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"drive.google.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"drive.google.com\"})",
     "legendFormat": "{{Drive}}"
    },
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"photos.google.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"photos.google.com\"})",
     "legendFormat": "{{photos}}"
    },
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"blogger.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"blogger.com\"})",
     "legendFormat": "{{blogger}}"
    }
   ]
  },
  {
   "title": "Porcentagem de perda de ping - Serviços do Google",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"mail.google.com\"}",
     "legendFormat": "{{Gmail}} IP:{{ip}}"
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"docs.google.com\"}",
     "legendFormat": "{{Docs}} IP:{{ip}}"
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"drive.google.com\"}",
     "legendFormat": "{{Drive}} IP:{{ip}}"
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"photos.google.com\"}",
     "legendFormat": "{{Photos}} IP:{{ip}}"
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"blogger.com\"}",
     "legendFormat": "{{Blogger}} IP:{{ip}}"
    }
   ]
  },
  {
   "title": "Tempo de Ida e Volta (RTT) - Redes Sociais",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"facebook.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"facebook.com\"})",
     "legendFormat": "{{facebook}}"
    },
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"twitter.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"twitter.com\"})",
     "legendFormat": "{{twitter}}"
    },
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"instagram.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"instagram.com\"})",
     "legendFormat": "{{instagram}}"
    },
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"whatsapp.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"whatsapp.com\"})",
     "legendFormat": "{{whatsapp}}"
    },
    {
     "expr": "sum(ping_rtt_ms{instance=\"$Instance\", target=\"linkedin.com\", ip_version=\"4\"}) / count(ping_rtt_ms{target=\"linkedin.com\"})",
     "legendFormat": "{{linkedin}}"
    }
   ]
  },
  {
   "title": "Porcentagem de perda de ping - Redes Sociais",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"facebook.com\"}",
     "legendFormat": "IPV{{ip_version}} {{target}} "
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"instagram.com\"}",
     "legendFormat": "IPV{{ip_version}} {{target}} "
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"twitter.com\"}",
     "legendFormat": "IPV{{ip_version}} {{target}} "
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"whatsapp.com\"}",
     "legendFormat": "IPV{{ip_version}} {{target}} "
    },
    {
     "expr": "ping_loss_percent{instance=\"$Instance\", target=\"linkedin.com\"}",
     "legendFormat": "IPV{{ip_version}} {{target}} "
    }
   ]
  }
 ]
}