apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoramento
spec:
  selector:
    app: grafana-deployment
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer