apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistentvolumeclaim
  namespace: monitoramento
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
