apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: regionalpd-storageclass