apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-persistentvolumeclaim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: regionalpd-storageclass