apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-service
spec:
  selector:
    app: grafana-deployment
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000