apiVersion: v1
kind: Service
metadata:
  name: consul-service
  namespace: monitoring
spec:
  selector:
    app: consul-deploy
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30085
  type: NodePort