apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: regionalpd-storageclass
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
parameters:
  type: pd-standard
  zones: us-central1-c